import { 
  MdOutlineCalendarMonth, 
  MdEvent, 
  MdArrowForward, 
  MdKeyboardArrowDown,
  MdKeyboardArrowRight, 
  MdKeyboardArrowLeft,
  MdOutlineDashboard,
  MdOutlineManageAccounts,
  MdOutlineSettings,
  MdOutlineLocationOn,
  MdOutlineAccessTime,
  MdOutlineShoppingBag,
  MdOutlineEventNote,
  MdArrowBack,
  MdLogout,
  MdCheckCircleOutline, 
  MdAccessTime,
  MdClose,
  MdOutlineStarBorder,
  MdLightbulbOutline,
  MdWorkOutline,
  MdOutlineSupervisorAccount,
  MdWorkspacePremium,
  MdOutlineTravelExplore,
  MdMenu,
  MdOutlineEdit,
  MdDeleteOutline,
  MdOutlineArrowCircleRight,
  MdChecklist,
  MdOutlineSearch,
} from "react-icons/md";

import { 
  FaUser, 
  FaLocationDot,
  FaSquareXTwitter,
  FaSquareInstagram,
  FaSquareFacebook,
  FaLinkedin,
  FaSquareWhatsapp,
  FaSquareYoutube,
  FaUsers,
  FaUserCheck,
  FaEnvelopeOpenText,
  FaRegFileLines,
  FaPencil,
  FaHandshakeSimple,
  FaUserPen,
  FaHandPointer,
} from "react-icons/fa6";

export const ICON_REGISTRY = {
  dashboard: MdOutlineDashboard,
  management: MdOutlineManageAccounts,
  settings: MdOutlineSettings,
  calendar: MdOutlineCalendarMonth,
  event: MdEvent,
  arrow: MdArrowForward,
  faLocation: FaLocationDot,
  dropdown: MdKeyboardArrowDown,
  arrowRight: MdKeyboardArrowRight,
  arrowLeft: MdKeyboardArrowLeft,
  location: MdOutlineLocationOn,
  hour: MdOutlineAccessTime,
  Opportunities: MdOutlineShoppingBag,
  bag: MdWorkOutline,
  applicants:MdOutlineEventNote,
  backArrow:MdArrowBack,
  logout: MdLogout,
  checkCircle:MdCheckCircleOutline,
  time:MdAccessTime,
  hamburger:MdMenu,
  close: MdClose,
  star: MdOutlineStarBorder,
  bulb: MdLightbulbOutline,
  users: MdOutlineSupervisorAccount,
  reward: MdWorkspacePremium,
  explore: MdOutlineTravelExplore,
  edit: MdOutlineEdit,
  delete: MdDeleteOutline,
  attempt:MdOutlineArrowCircleRight,
  score: MdChecklist,
  search: MdOutlineSearch,

  // Fontawesome Icons
  user: FaUser,
  group: FaUsers,
  usercheck: FaUserCheck,
  userpen: FaUserPen,
  envelope:FaEnvelopeOpenText,
  file:FaRegFileLines,
  pencil: FaPencil,
  pointer: FaHandPointer,
  handshake: FaHandshakeSimple,
  twitter:FaSquareXTwitter,
  instagram:FaSquareInstagram,
  facebook:FaSquareFacebook,
  linkedin:FaLinkedin,
  whatsapp:FaSquareWhatsapp,
  youtube:FaSquareYoutube,
};